services:
  app-harmonia:
    image: app-harmonia:v0.1
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-harmonia
    volumes:
      - ./backend/:/app
    ports:
      - "55030:50052"
    stdin_open: true
    tty: true
    env_file:
    - ./backend/.env
    networks:
        - harmonia-network
networks:
  harmonia-network:
    name: harmonia-network
    external: true

